spring:
  application:
    name: mry-learn
  output:
    ansi:
      enabled: always
  threads:
    virtual:
      enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  data:
    mongodb:
      uri: mongodb://localhost:27017/local_db
    redis:
      host: localhost
      port: 6379
      password: redispw
  cache:
    type: redis
  security:
    oauth2:
      authorizationserver:
        cookie-setup-domain: dev.aa.com
      client:
        registration:
          wechat-pc:
            # SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_WECHAT_PC_CLIENT_ID
            client-id: masked
            # SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_WECHAT_PC_CLIENT_SECRET
            client-secret: masked
          wechat-mobile:
            client-id: masked
            client-secret: masked
        provider:
          wechat-pc:
            user-info-uri: https://api.weixin.qq.com/sns/userinfo
            token-uri: https://api.weixin.qq.com/sns/oauth2/access_token
            user-info-authentication-method: authorization_code
          wechat-mobile:
            user-info-uri: https://api.weixin.qq.com/sns/userinfo
            token-uri: https://api.weixin.qq.com/sns/oauth2/access_token
            user-info-authentication-method: authorization_code
  mail:
    host: smtp.qq.com
    port: 465
    # SPRING_MAIL_USERNAME=env;
    # SPRING_MAIL_PASSWORD=env;
    username: masked
    password: masked
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
  # SPRING_MESSAGES_ALI_YUN_ACCESS_KEY
  # SPRING_MESSAGES_ALI_YUN_SECRET
  # SPRING_MESSAGES_ALI_YUN_SMS_SIGN_NAME
  # SPRING_MESSAGES_ALI_YUN_SMS_TEMPLATE_CODE
  messages:
    ali-yun:
      sms-sign-name: masked
      sms-template-code: masked
      access-key: masked
      secret: masked
eventuate:
  redis:
    # noinspection SpringBootApplicationYaml
    servers: localhost:6380
    # noinspection SpringBootApplicationYaml
    partitions: 2
logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: debug
    org.springframework.data.mongodb.core.MongoTemplate: debug
    org.springframework.jdbc.core.StatementCreatorUtils: trace
    io.netty.resolver.dns.DnsServerAddressStreamProviders: error