spring:
  application:
    name: mry-learn
  profiles:
    active:
      - Redis
      - PostgresWal
  output:
    ansi:
      enabled: always
  threads:
    virtual:
      enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  data:
    mongodb:
      host: localhost
      port: 27017
      username: root
      password: root
      authentication-database: admin
      database: local_db
    #      uri: mongodb://mongo:mongo@localhost:27017/local_db
    redis:
      host: localhost
      port: 6379
      password: redispw
#      password: recommend-Pa55wd
#      cluster:
#        nodes:
#          - 172.16.157.202:6379
#          - 172.16.112.205:6379
#          - 172.16.238.56:6379
#          - 172.16.157.222:6379
#          - 172.16.112.201:6379
#          - 172.16.238.24:6379
  cache:
    type: redis
  security:
    oauth2:
      authorizationserver:
        cookie-setup-domain: dev.aa.com
      client:
        registration:
          wechat-pc:
            # SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_WECHAT_PC_CLIENT_ID
            client-id: masked
            # SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_WECHAT_PC_CLIENT_SECRET
            client-secret: masked
          wechat-mobile:
            client-id: masked
            client-secret: masked
        provider:
          wechat-pc:
            user-info-uri: https://api.weixin.qq.com/sns/userinfo
            token-uri: https://api.weixin.qq.com/sns/oauth2/access_token
            user-info-authentication-method: authorization_code
          wechat-mobile:
            user-info-uri: https://api.weixin.qq.com/sns/userinfo
            token-uri: https://api.weixin.qq.com/sns/oauth2/access_token
            user-info-authentication-method: authorization_code
  mail:
    host: smtp.qq.com
    port: 465
    # SPRING_MAIL_USERNAME=env;
    # SPRING_MAIL_PASSWORD=env;
    username: masked
    password: masked
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
  # SPRING_MESSAGES_ALI_YUN_ACCESS_KEY
  # SPRING_MESSAGES_ALI_YUN_SECRET
  # SPRING_MESSAGES_ALI_YUN_SMS_SIGN_NAME
  # SPRING_MESSAGES_ALI_YUN_SMS_TEMPLATE_CODE
  messages:
    ali-yun:
      sms-sign-name: masked
      sms-template-code: masked
      access-key: masked
      secret: masked

eventuate:
  cdc:
    reader:
      reader1:
        type: postgres-wal
        datasourceurl: ${spring.datasource.url}
        datasourceusername: ${spring.datasource.username}
        datasourcepassword: ${spring.datasource.password}
        datasourcedriverclassname: ${spring.datasource.driver-class-name}
        outboxid: 1
        leadershiplockpath: /eventuatelocal/cdc/leader/pipeline/1
    pipeline:
      pipeline1:
        type: eventuate-tram
        reader: reader1

logging:
  level:
    io.eventuate: INFO
    org.springframework.data.mongodb.core.MongoTemplate: debug
#    org.springframework.jdbc.core.JdbcTemplate: debug
#    org.springframework.jdbc.core.StatementCreatorUtils: trace
    io.netty.resolver.dns.DnsServerAddressStreamProviders: error
