spring:
  application:
    name: mry-learn
  output:
    ansi:
      enabled: always
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  data:
    mongodb:
      uri: mongodb://localhost:27017/mry_local_db

eventuate:
  redis:
    servers: localhost:6379
    partitions: 1

logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: debug
    org.springframework.jdbc.core.StatementCreatorUtils: trace
